# Generated by Django 3.1.7 on 2021-03-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='avatoar',
            new_name='avatar',
        ),
    ]
